apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/test1
  persistentVolumeReclaimPolicy: Retain
# persistentVolumeReclaimPolicy: Delete
# persistentVolumeReclaimPolicy: Recycle









